version: '2.1'

services:
  train:
    build: ./train
    privileged: true
    restart: always
    labels:
      io.balena.features.balena-api: '1'
  audio:
    image: balenablocks/audio:raspberrypi4-64  # See supported devices for other archs
    privileged: true
    labels:
      io.balena.features.dbus: 1  # Only required for bluetooth support